[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13", features = ["dynamic_linking"] }
rand = "0.7.3"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[alias]
run = 'run --feature "bevy/dynamic_linking"'
